namespace TscStatement.Common.Enums
{
    public class NpoiCellColor
    {
        public enum CellColor
        {
            Black = 8,
            Brown = 60,
            Olive_Green = 59,
            Dark_Green = 58,
            Dark_Teal = 56,
            Dark_Blue = 18,
            Indigo =62,
            Grey_80_PERCENT = 63,
            Dark_Red = 16,
            Orange = 53,
            DARK_YELLOW = 19,
            Green = 17,
            Teal = 21,
            Blue = 12,
            Blue_Grey = 54,
            Grey_50_PERCENT = 23,
            Red = 10,
            LIGHT_ORANGE = 52,
            LIME = 50,
            SEA_GREEN = 57,
            AQUA = 49,
            LIGHT_BLUE = 48,
            VIOLET = 20,
            GREY_40_PERCENT = 55,
            Pink = 14,
            Gold = 51,
            Yellow = 13,
            BRIGHT_GREEN = 11,
            TURQUOISE = 15,
            SKY_BLUE = 40,
            Plum = 61,
            GREY_25_PERCENT = 22,
            Rose = 45,
            Tan = 47,
            LIGHT_YELLOW = 43,
            LIGHT_GREEN = 42,
            LIGHT_TURQUOISE = 41,
            PALE_BLUE = 44,
            LAVENDER = 46,
            White = 9,
            CORNFLOWER_BLUE = 24,
            LEMON_CHIFFON = 26,
            MAROON = 25,
            ORCHID = 28,
            CORAL = 29,
            ROYAL_BLUE = 30,
            LIGHT_CORNFLOWER_BLUE = 31,
            AUTOMATIC = 64,
        }
    }
}